AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  chessfinder caching with dynamodb

Resources:
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: users
      AttributeDefinitions:
        - AttributeName: user_name
          AttributeType: S
        - AttributeName: platform
          AttributeType: S
      KeySchema:
        - AttributeName: user_name
          KeyType: HASH
        - AttributeName: platform
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
  TasksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: tasks
      AttributeDefinitions:
        - AttributeName: task_id
          AttributeType: S
      KeySchema:
        - AttributeName: task_id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 2
  GamesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: games
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: game_id
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: game_id
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 10
        WriteCapacityUnits: 10

Outputs:
  UsersTableName:
    Description: "Users Table Name"
    Value: !Ref UsersTable
  TasksTableName:
    Description: "Tasks Table Name"
    Value: !Ref TasksTable
  GamesTableName:
    Description: "Games Table Name"
    Value: !Ref GamesTable