version: '3.9'

services:

  wiremock:
    image: wiremock/wiremock:latest
    container_name: wiremock
    restart: "no"
    hostname: wiremock
    ports:
      - "${WIREMOCK_EXPOSED_PORT}:8443"
    command:
      [
        "--port",
        "8443",
        "--max-request-journal",
        "1000",
        "--local-response-templating",
        "--root-dir",
        "/home/wiremock/storage"
      ]

#   dynamodb:
#     image: amazon/dynamodb-local:latest
#     command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data"
#     container_name: dynamodb
#     restart: always
#     hostname: dynamodb
#     ports:
#       - "${DYNAMO_DB_EXTERNAL_PORT}:8000"
#     volumes:
#       - ${STORAGE}/dynamodb:/home/dynamodblocal/data
#     depends_on:
#       liquibase:
#         condition: service_completed_successfully

#   dynamodb-admin:
#     image: aaronshaf/dynamodb-admin:latest
#     container_name: dynamodb_admin
#     restart: always
#     hostname: dynamodb-admin
#     ports:
#       - "${DYNAMO_DB_ADMIN_PORT}:8001"
#     environment:
#       DYNAMO_ENDPOINT: http://dynamodb:8000
#       AWS_REGION: ${AWS_REGION}
# #      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
# #      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
#     depends_on:
#       - dynamodb
