name: Deploy Prod

on:
  push:
    tags: 
      - '**'

jobs:
  releasing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Derive Tag
        run: |
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "release_version=$GITHUB_REF_NAME" >> $GITHUB_ENV
      - name: Create release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.release_version }}
          release_name: Release ${{ env.release_version }}
          body: |
            This release contains changes for version ${{ env.release_version }}.
          draft: false
          prerelease: false
     
      - name: Deploying to Prod
        run: |
          # sbt 'runMain chessfinder.SamTemplate' assembly
          # 
          echo "Deploy to Prod"