name: Pull Request

on:
  pull_request:
    branches: [trunk]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v3.11.0
        with:
          distribution: 'corretto'
          java-version: '11'
      - name: Check Fomatting
        shell: bash
        run: |
          # sbt -v "scalafmtCheckAll;"
          sbt -v "compile;"
      - name: Compile Code
        shell: bash
        run: |
          sbt -v "compile;"
      - name: Test Code
        shell: bash
        run: |
          # sbt -v "test;"
          sbt -v "compile;"
