name: Tagging

on:
  push:
    branches: [master]
    path: [version]

jobs:
  tagging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Read version file
        id: read_version
        run: echo "app_version=$(cat version)" >> $GITHUB_ENV
      - uses: rickstaa/action-create-tag@v1.6.1
        id: "tag_create"
        with:
          tag: ${{ env.app_version }}
          tag_exists_error: false
          message: "Tagged: ${{ env.app_version }}"